Repository KyoriPowered/adventure-webui, pull requests merged in 2022-02, with the labels that each got.

#77 Update build.yml
  .github/workflows/build.yml
Labels: area: build

#68 Begin updating for MM changes in adventure 4.10.0
  gradle/libs.versions.conf
  src/commonMain/kotlin/net/kyori/adventure/webui/websocket/Packet.kt
  src/commonMain/resources/web/index.html
  src/jsMain/kotlin/net/kyori/adventure/webui/js/Main.kt
  src/jsMain/kotlin/net/kyori/adventure/webui/js/UserPlaceholder.kt
  src/jvmMain/kotlin/net/kyori/adventure/webui/jvm/minimessage/MiniMessage.kt
  src/jvmMain/resources/application.conf
Labels: area: backend, type: dependencies

#78 common: Fix style of server list and lore
  src/commonMain/resources/web/css/style.css
Labels: type: bug, area: frontend

#79 Revamp server list to include header in HTML, not when parsing
  src/commonMain/resources/web/css/style.css
  src/commonMain/resources/web/index.html
  src/jsMain/kotlin/net/kyori/adventure/webui/js/Main.kt
Labels: area: frontend, type: enhancement

#80 Fix: JSON and tree exports not using placeholders
  src/jsMain/kotlin/net/kyori/adventure/webui/js/Main.kt
Labels: type: bug, area: frontend

#81 Only handle newlines as separate parses when in lore mode
  src/commonMain/kotlin/net/kyori/adventure/webui/websocket/Packet.kt
  src/jsMain/kotlin/net/kyori/adventure/webui/js/Main.kt
  src/jvmMain/kotlin/net/kyori/adventure/webui/jvm/minimessage/MiniMessage.kt
Labels: area: frontend, area: backend, type: enhancement

#83 fix: re-parse when switching modes
  src/jsMain/kotlin/net/kyori/adventure/webui/js/Main.kt
Labels: type: bug, area: frontend

#84 feature: Ping icon on server list mode
  src/commonMain/resources/web/css/style.css
  src/commonMain/resources/web/img/ping.png
  src/commonMain/resources/web/index.html
Labels: area: frontend, type: enhancement
