Repository KyoriPowered/adventure-webui, pull requests merged in 2022-03, with the labels that each got.

#85 chore: Miscellaneous build changes
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  build.gradle.kts
  gradle/libs.versions.conf
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: area: build

#93 fix: Try-catch around constructing placeholders
  src/jvmMain/kotlin/net/kyori/adventure/webui/jvm/minimessage/MiniMessage.kt
  src/jvmMain/kotlin/net/kyori/adventure/webui/jvm/minimessage/editor/EditorRoute.kt
Labels: type: bug, area: backend

#95 feat: Validate tag syntax in frontend and explain why a tag would be invalid
  src/commonMain/resources/web/css/style.css
  src/commonMain/resources/web/index.html
  src/jsMain/kotlin/net/kyori/adventure/webui/js/UserPlaceholder.kt
Labels: area: frontend, type: enhancement
